config/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name="home"),
    url(r'^blog/', include('myblog.apps.blog.urls', namespace="blog")),
    url(r'^custom-auth/', include('myblog.apps.accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^api/comment/', include('myblog.apps.comment.api.urls', namespace='comment-api')),
    url(r'^api/post/', include('myblog.apps.blog.api.urls', namespace='post-api')),
    url(r'^admin/', admin.site.urls),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

myblog/apps/blog/api/urls.py
from django.conf.urls import url, include

from .views import (
    PostCreateAPIView,
    PostListAPIView, 
    PostDetailAPIView, 
    PostUpdateAPIView, 
    PostDeleteAPIView
)


urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name='list'),
    url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    url(r'^(?P<slug>[-\w]+)/$', PostDetailAPIView.as_view(), name='detail'),
    url(r'^(?P<slug>[-\w]+)/update/$', PostUpdateAPIView.as_view(), name='update'),
    url(r'^(?P<slug>[-\w]+)/delete/$', PostDeleteAPIView.as_view(), name='delete'),
]

myblog/apps/blog/urls.py
from django.conf.urls import url
from .views import CreatePostView, ListPostView, post_detail_view, PostUpdateView, DeletePostView

urlpatterns = [
    url(r'^$', ListPostView.as_view(), name='home'),
    url(r'^create/$', CreatePostView.as_view(), name='create'),
    url(r'^(?P<slug>[-\w]+)/$', post_detail_view, name='detail'),
    url(r'^(?P<slug>[-\w]+)/update/$', PostUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[-\w]+)/delete/$', DeletePostView.as_view(), name='delete'),
]

myblog/apps/blog/models.py
import datetime
import time
import math

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.text import slugify
from django.contrib.contenttypes.fields import ContentType

from myblog.apps.comment.models import Comment


def upload_location(instance, filename):
    return "blog/%s" % (filename)

@python_2_unicode_compatible
class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=140, verbose_name='Post Title')
    text = models.TextField(verbose_name='Body of Post')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Posted Date')
    updated = models.DateTimeField(auto_now=True, verbose_name='Updated Date')

    # for the image field. You need to install pillow for it to work
    width_field = models.IntegerField(default=0)
    height_field = models.IntegerField(default=0)
    image = models.ImageField(upload_to=upload_location, width_field='width_field', height_field='height_field', verbose_name='Your Image (Not More than 200kb)')

    # for us to publish at a time we wish even in the future.
    draft = models.BooleanField(default=False, verbose_name='Render Inactive')
    published = models.DateTimeField(auto_now=False, auto_now_add=False, verbose_name='Date to be Published')

    slug = models.SlugField(unique=True, max_length=140)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-created', '-updated']

    def get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num +=1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.get_unique_slug()
        super().save()

    # returns all comments for this particular 'self' post
    @property
    def comment(self):
        return Comment.objects.comment_by_instance(self)

    @property
    def get_content_type(self):
        return ContentType.objects.get_for_model(self.__class__)

myblog/apps/blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    published = forms.DateTimeField(widget=forms.SelectDateWidget())
    class Meta:
        fields = ['image', 'title', 'text', 'draft', 'published']
        model = Post

myblog/apps/blog/api/views.py
from rest_framework.generics import (
    CreateAPIView,
    ListAPIView,
    RetrieveAPIView,
    UpdateAPIView,
    RetrieveUpdateAPIView,
    RetrieveDestroyAPIView,
    DestroyAPIView
)

from rest_framework.permissions import (
    IsAdminUser,
    IsAuthenticated,
    IsAuthenticatedOrReadOnly,
    AllowAny
)
from rest_framework.filters import SearchFilter, OrderingFilter

from myblog.apps.blog.models import Post
from .serializers import (
    PostListSerializer,
    PostDetailSerializer,
    PostCreateSerializer,
    PostUpdateSerializer,
    PostDeleteSerializer
)
from .permissions import IsOwnerOrReadOnly
from .paginations import PostListLimitOffsetPagination, PostListPageNumberPagination


class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateSerializer
    permission_classes = [AllowAny]

    # associate the created post with the user
    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


class PostListAPIView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['text', 'slug', 'author__username']
    pagination_class = PostListPageNumberPagination


class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'
    permission_classes = [IsAuthenticated]

class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostUpdateSerializer
    lookup_field = 'slug'
    permission_classes = [IsAuthenticated]

    # def perform_update(self, serializer):
    #     serializer.save(author=self.request.user)


class PostDeleteAPIView(RetrieveDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDeleteSerializer
    lookup_field = 'slug'
    permission_classes = [IsAuthenticated]

myblog/apps/blog/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.core.urlresolvers import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView, FormView
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType

from .models import Post
from .forms import PostForm
from myblog.apps.comment.models import Comment
from myblog.apps.comment.forms import CommentForm

from .mixins import QuerysetModelMixin
from braces import views

#create a post
class CreatePostView(CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:home')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.draft = False
        form.instance.published = timezone.now()
        return super(CreatePostView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "CREATE A NEW POST"
        return context



#list all the posts
class ListPostView(ListView):
    model = Post
    paginate_by = 3

    def get_queryset(self):
        return Post.objects.filter(published__lte=timezone.now(), draft=False)

    def get_context_data(self, **kwargs):
        context = super(ListPostView, self).get_context_data(**kwargs)
        context['title'] = "Hello My Blog Home Page"
        return context


def post_detail_view(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)

    form = CommentForm(request.POST or None)
    parent_id = None
    parent_of_reply = None

    try:
        parent_id = int(request.POST.get("parent_id"))
    except:
        parent_id = None
        
    if parent_id:
        parent = Comment.objects.filter(id=parent_id)
        if parent.exists():
            parent_of_reply = parent.first()

    if form.is_valid():
        Comment.objects.get_or_create(
            user = request.user,
            content_type = instance.get_content_type,
            object_id = instance.id,
            comment_text = form.cleaned_data.get("content"),
            parent = parent_of_reply,
            )
        form = CommentForm()

    context = {
        "comments": instance.comment,
        "instance": instance,
        "form": form
    }
    return render(request, "blog/post_detail.html", context)
        

#update the post
class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Update POST NOW!!"
        return context
    
    # permission_required = "auth.change_user"
    # form_class = PostForm


#delete post
class DeletePostView(DeleteView):
    model = Post
    success_url = '/'

myblog/apps/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/post_list.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block navbar_collapse %}
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
            <a href="#page-top"></a>
        </li>
        <li class="page-scroll">
            <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'home' %}">Home</a>
        </li>
        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'blog:home' %}">Blog</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="page-scroll active">
            <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'logout' %}"><span class="fa fa-user"></span> Logout</a>
        </li>

        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'blog:create' %}">Create Post</a>
        </li>
        {% else %}
        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'login' %}">Login</a>
        </li>

        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'register' %}">SignUp</a>
        </li>
         {% endif %}
        <li class="page-scroll">
                <form method="GET" action="" role="form" class="form-inline">
<div class="form-group"><label for="search"></label>
<input type="text" class="form-control" id="search" name="query_field" placeholder="Search...." value="{{ request.Get.query_field }}" style="width:150px;"/>
</div><button type="submit" class="btn btn-default">Go</button>
                        </form>
        </li>
    </ul>
</div>
{% endblock %}
<!-- /.navbar-collapse -->


{% block content %}
<section>
<div class="row">
<div class="container">
<div class="col-md-4">
           <!-- for messages framework -->
           {% if messages %}
           <ul class="messages">
               {% for message in messages %}
               <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
               {% if "html_safe" in message.tags %}
               {{message|safe}}
               {% else %}   
               {{ message }}
                {% endif %}
            </li>
               {% endfor %}
           </ul>
           {% endif %}
</div>
</div>
</div>    
</section>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
    <span class="text-center text-danger">Are You sure you want to delete "{{object}}" ?</span>
    <input type="submit" value="Confirm >>" class='btn btn-danger btn-block'/>
    </form>
       </div>
    </div>

    <br/>
{% endblock %}

myblog/apps/blog/templates/blog/post_detail.html
{% extends 'blog/post_list.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block navbar_collapse %}
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
            <a href="#page-top"></a>
        </li>
        <li class="page-scroll">
            <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'home' %}">Home</a>
        </li>
        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'blog:home' %}">Blog</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="page-scroll active">
            <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'logout' %}"><span class="fa fa-user"></span> Logout</a>
        </li>

        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'blog:create' %}">Create Post</a>
        </li>
        {% else %}
        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'login' %}">Login</a>
        </li>

        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'register' %}">SignUp</a>
        </li>
         {% endif %}
        <li class="page-scroll">
                <form method="GET" action="" role="form" class="form-inline">
<div class="form-group"><label for="search"></label>
<input type="text" class="form-control" id="search" name="query_field" placeholder="Search...." value="{{ request.Get.query_field }}" style="width:150px;"/>
</div><button type="submit" class="btn btn-default">Go</button>
                        </form>
        </li>
    </ul>
</div>
{% endblock %}
<!-- /.navbar-collapse -->


{% block content %}
<section class="row">
<div class="container">
<div class="col-md-4">
           <!-- for messages framework -->
           {% if messages %}
           <ul class="messages">
               {% for message in messages %}
               <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
               {% if "html_safe" in message.tags %}
               {{message|safe}}
               {% else %}   
               {{ message }}
                {% endif %}
            </li>
               {% endfor %}
           </ul>
           {% endif %}
</div>
</div>  
</section>

<div class="row">
    <div class="col-xs-12 text-center">
       <div class="thumbnail">
            {% if instance.image %}
            <img src="{{instance.image.url}}" style="max-width:60%; max-height:30%;" class="img-responsive" />
            {% endif %}
<div class="caption">
        <h1 style="color:orange">{{instance.title}} </h1>
        <p style="color:lightseagreen">{{instance.text | safe}}</p>
        <br/>
        <i>Published at: 
            <span style="color:palevioletred">{{instance.published|date}}</span></i>
        <br/> <br/>

        {% if instance.user.get_full_name %}
        <i>Author: {{instance.user.get_full_name}}</i>
        {% else %}
        <i>Author: {{instance.author}}</i>
        {% endif %}

        <br/>  <br/>
        <hr>
</div>
       </div>
    </div>
    </div>
<br/>
<br/>
    <div class="row">
        <div class="col-md-6 col-md-offset-4">
            {% if comments.count > 0 %}
            <h4> {{comments.count}} Comments</h4><br/>
            {% else %}
            <h5>Comments</h5><br/>
            {% endif %}
         <!-- comments for loop -->
                    {% for comment in comments %}
            <blockquote style="border-left:5px solid rgb(7, 88, 109)">

                <!-- comment owner div -->
                <div class="pull-left">
                    <img src="{% static 'image/user.png' %}" class="img-thumbnail img-circle" width="60" height="40"/>
                        {{comment.user}}:
                </div>
                <br/>

             <!-- comment text div -->
                <div class="text-center">
                    {{comment.comment_text}}
                </div>

             <!-- comment footer div -->
                <footer>
        <small class="text-center"><a href="#" class="reply-block-btn">Reply 
                <span class="badge">{% if comment.replies.count > 0 %} {{comment.replies.count}} {% endif %}</span> 
            </a></small>
            
            <small class="pull-right">{{comment.commented_at|timesince}}</small>
                </footer>

                             <!-- comment replies block -->
                <div class="row reply-block">
                        <blockquote>
                                     <!-- replies for loop -->
                             {% for reply in comment.replies %}
                             <div class="col-md-8 col-md-offset-4">
                                <div style="border-left:5px solid rgb(62, 202, 172)">
                                    <div class="pull-left" >
                                        <img src="{% static 'image/user.png' %}" class="img-thumbnail img-circle" width="60" height="40"/>
                                        {% if request.user %}
                                        {{request.user}}:
                                        {% endif %}
                                    </div>
                                        <br/>
                                        <div class="text-center">
                                        {{ reply.comment_text }}
                                        </div>
                                    <hr>
                                    </div>                            
                             </div>
                             <br/>
                             {% endfor %}
                        <!--end replies for loop -->

                        <!-- replies form -->
                             <div class="col-md-6 col-md-offset-3">
                                 <h4>Reply</h4>
                                <form method="post" action=".">
                                    {% csrf_token %}
                                    {{form|crispy}}
                              <input type="hidden" name="parent_id" value="{{comment.id}}"/>
                              <input type="submit" value="Reply" class="btn btn-success"/>
                                </form>
                             </div>
                         </blockquote>
                 <hr>
                </div>
            <!-- end replies block -->

            </blockquote>   <!-- end comments blockquote -->
            {% endfor %}
            <br/>

            <h4>Comment</h4>
            <form method="post" action=".">
                {% csrf_token %}
                {{form|crispy}}
          <input type="submit" value="Comment" class='btn btn-success'/>
            </form>

            <br/>
        </div>
    </div>

<br/>
    <hr>


{% if request.user.is_authenticated %}
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="col-xs-3">
                <a href="{% url 'blog:create' %}" class="btn btn-primary"><span class="fa fa-plus"></span> New Post</a>
            </div>
            <div class="col-xs-3">
                <a href="update/" class="btn btn-success">Edit Post</a>
            </div>
            <div class="col-xs-3">
                <a href="delete/" class="btn btn-danger">Delete Post</a>
            </div>
            <div class="col-xs-3">
                <a href="{% url 'blog:home' %}" class="btn btn-info">Go Home</a>
            </div>
        </div>
    </div>
{% endif %}
    <br/> <br/>

 <!-- Footer -->
 <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    
                    <div class="footer-col col-md-4 col-md-offset-4">
                        <h3>Around the Web</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="https://www.facebook.com/abdulwahabawudu99" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                            </li>

                            <li>
                                <a href="https://www.twitter.com/wahab_awudu" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                            </li>

                            <li>
                                <a href="https://www.googleplus.com/+wahabawudu" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>

                            <li>
                                <a href="https://www.linkedin.com/wahabawudu" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; abdulwahab <span id="full-year"></span>
                        <script>
                        var date = new Date();
                        document.getElementById("full-year").innerHTML=date.getFullYear();
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}

myblog/apps/blog/templates/blog/post_form.html
{% extends 'blog/post_list.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block navbar_collapse %}
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
            <a href="#page-top"></a>
        </li>
        <li class="page-scroll">
            <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'home' %}">Home</a>
        </li>
        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'blog:home' %}">Blog</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="page-scroll active">
            <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'logout' %}"><span class="fa fa-user"></span> Logout</a>
        </li>

        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'blog:create' %}">Create Post</a>
        </li>
        {% else %}
        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'login' %}">Login</a>
        </li>

        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'register' %}">SignUp</a>
        </li>
         {% endif %}
        <li class="page-scroll">
                <form method="GET" action="" role="form" class="form-inline">
<div class="form-group"><label for="search"></label>
<input type="text" class="form-control" id="search" name="query_field" placeholder="Search...." value="{{ request.Get.query_field }}" style="width:150px;"/>
</div><button type="submit" class="btn btn-default">Go</button>
                        </form>
        </li>
    </ul>
</div>
{% endblock %}
<!-- /.navbar-collapse -->


{% block content %}
<section>
    <h1 class="text-center text-info">{{page_title}}</h1>
    <div class="row">
        <div class="container">
        <div class="col-md-8 col-md-offset-2">
            <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Publish Post >>" class='btn btn-success btn-block'/>            
            </form>
        </div>
        </div>
    </div>
</section>
<br/>   
{% endblock %}

myblog/apps/blog/templates/blog/post_form_update.html
{% extends 'blog/post_list.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block navbar_collapse %}
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
            <a href="#page-top"></a>
        </li>
        <li class="page-scroll">
            <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'home' %}">Home</a>
        </li>
        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'blog:home' %}">Blog</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="page-scroll active">
            <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'logout' %}"><span class="fa fa-user"></span> Logout</a>
        </li>

        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'blog:create' %}">Create Post</a>
        </li>
        {% else %}
        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'login' %}">Login</a>
        </li>

        <li class="page-scroll active">
                <a data-toggle="collapse" data-target=".navbar-collapse.in" href="{% url 'register' %}">SignUp</a>
        </li>
         {% endif %}
        <li class="page-scroll">
                <form method="GET" action="" role="form" class="form-inline">
<div class="form-group"><label for="search"></label>
<input type="text" class="form-control" id="search" name="query_field" placeholder="Search...." value="{{ request.Get.query_field }}" style="width:150px;"/>
</div><button type="submit" class="btn btn-default">Go</button>
                        </form>
        </li>
    </ul>
</div>
{% endblock %}
<!-- /.navbar-collapse -->


{% block content %}
<section>
    <h1 class="text-center text-info">{{page_title}}</h1>
    <div class="row">
        <div class="container">
        <div class="col-md-8 col-md-offset-2">
            <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Publish Post >>" class='btn btn-success btn-block'/>            
            </form>
        </div>
        </div>
    </div>
</section>
<br/>   
{% endblock %}